name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt
          pip install pytest boto3

      - name: Create deployment package
        run: bash create_deployment_package.sh

      - name: Run tests
        run: |
          pytest lambda/tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

      - name: Initialize and apply Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          path: terraform
          backend_config_file: backend.tfvars
          var_file: terraform.tfvars
          workspace: default
          terraform_version: 0.12.26
